// Generated by tools/export-dashboard-data.ps1 on 2026-06-01 13:26:37.
// Source episode: episodes\001-pilot
// Copy EPISODE into app/reel-it-in.html, or run this script with -UpdateDashboard.
const EPISODE = {
    "number":  "001",
    "label":  "Pilot",
    "date":  "2026-06-01",
    "hosts":  {
                  "you":  "Shane",
                  "dad":  "Dad"
              },
    "news":  [
                 {
                     "source":  "Google I/O 2026 announcements",
                     "url":  "https://blog.google/innovation-and-ai/technology/ai/google-io-2026-all-our-announcements/",
                     "headline":  "Google wants AI to stop just answering and start doing things for you.",
                     "why":  "This is the moment AI starts feeling less like a chatbot and more like a helper embedded in products people already use.",
                     "dadQuestion":  "When you say it can \"act,\" what is it actually allowed to do?",
                     "status":  "Selected"
                 },
                 {
                     "source":  "Microsoft Security: Defense at AI speed",
                     "url":  "https://www.microsoft.com/en-us/security/blog/2026/05/12/defense-at-ai-speed-microsofts-new-multi-model-agentic-security-system-tops-leading-industry-benchmark/",
                     "headline":  "Microsoft says AI agents helped find serious Windows security holes.",
                     "why":  "AI is not just writing code now; it is starting to inspect the digital plumbing we all depend on. That could help defenders, but it also raises the obvious question of what attackers can do with similar tools.",
                     "dadQuestion":  "If AI can find those flaws, can criminals use it to find them too?",
                     "status":  "Selected"
                 },
                 {
                     "source":  "European Commission AI transparency consultation",
                     "url":  "https://digital-strategy.ec.europa.eu/en/news/commission-opens-consultation-draft-guidelines-ai-transparency-obligations",
                     "headline":  "Europe is moving toward labels for AI conversations and AI-made media.",
                     "why":  "The internet is about to need ingredient labels. The hard part is deciding what must be labeled, who checks it, and whether normal people will trust the labels.",
                     "dadQuestion":  "Would a label make you trust something more, or just make you wonder what else is unlabeled?",
                     "status":  "Selected"
                 }
             ],
    "featuredSparks":  [
                           "whose-opinions",
                           "oracle",
                           "the-state",
                           "where-it-lives",
                           "who-owns-temple"
                       ]
};

// Custom sparks that are not in the dashboard's SPARK_LIBRARY yet.
// Add these to SPARK_LIBRARY before using their ids in featuredSparks.
const GENERATED_SPARKS = {

};
