// Generated by tools/export-dashboard-data.ps1 on 2026-06-11 06:54:30.
// Source episode: /home/ark/reel-it-in/episodes/001-pilot
// Copy EPISODE into app/reel-it-in.html, or run this script with -UpdateDashboard.
const EPISODE = {
  "number": "001",
  "label": "Pilot",
  "date": "2026-06-01",
  "hosts": {
    "you": "Shane",
    "dad": "Dad"
  },
  "news": [
    {
      "source": "Google I/O 2026 announcements",
      "url": "https://blog.google/innovation-and-ai/technology/ai/google-io-2026-all-our-announcements/",
      "headline": "Google wants AI to stop just answering and start doing things for you.",
      "why": "This is the moment AI starts feeling less like a chatbot and more like a helper embedded in products people already use.",
      "dadQuestion": "When you say it can \"act,\" what is it actually allowed to do?",
      "status": "Selected",
      "xInsight": "- **What people are arguing about:** Did Google just kill the old search box, or is it the same product with more AI on top? Publishers and SEO folks warn that background “information agents” could mean fewer website visits; Google pushes back that blue links still exist, just farther from center stage.\n- **Representative angle:** Tech coverage keeps framing Gemini Spark as Google’s answer to OpenClaw — an always-on cloud agent that can watch your inbox and calendar even when your laptop is off, with permission checks before it does anything big.\n- **So what for listeners:** AI is moving into the apps you already use — search, shopping, email — and starting to handle small jobs, not just answer questions. Less keyword hunting, more delegating, if you’re okay with what it can see."
    },
    {
      "source": "Microsoft Security: Defense at AI speed",
      "url": "https://www.microsoft.com/en-us/security/blog/2026/05/12/defense-at-ai-speed-microsofts-new-multi-model-agentic-security-system-tops-leading-industry-benchmark/",
      "headline": "Microsoft says AI agents helped find serious Windows security holes.",
      "why": "AI is not just writing code now; it is starting to inspect the digital plumbing we all depend on. That could help defenders, but it also raises the obvious question of what attackers can do with similar tools.",
      "dadQuestion": "If AI can find those flaws, can criminals use it to find them too?",
      "status": "Selected",
      "xInsight": "- **The fight on X:** Real breakthrough or benchmark theater? Debate splits over self-reported CyberGym scores beating Anthropic's Mythos, whether 100-plus agents beat one big model, and whether the same bug-hunting kit works for attackers too.\n- **Representative angle:** Nadella's Patch Tuesday flex — AI agents found 16 Windows flaws, four critical, right before the fixes shipped. GeekWire summed it up as \"Mythos has been MDASH'd.\"\n- **So what:** AI isn't just writing code anymore; it's stress-testing the plumbing behind your laptop. That could patch holes faster — but the race to find them just sped up for everyone."
    },
    {
      "source": "European Commission AI transparency consultation",
      "url": "https://digital-strategy.ec.europa.eu/en/news/commission-opens-consultation-draft-guidelines-ai-transparency-obligations",
      "headline": "Europe is moving toward labels for AI conversations and AI-made media.",
      "why": "The internet is about to need ingredient labels. The hard part is deciding what must be labeled, who checks it, and whether normal people will trust the labels.",
      "dadQuestion": "Would a label make you trust something more, or just make you wonder what else is unlabeled?",
      "status": "Selected",
      "xInsight": "- **What people on X are arguing about:** Whether EU transparency rules will actually help people spot bots and deepfakes, or just add legal fine print platforms can game—while creators and lawyers fight over what counts as AI-generated, manipulated, or “public interest” content.\n- **Representative angle:** A recurring thread treats the August deadline like ingredient labels on the internet: fine in theory, but pointless if nobody reads them, watermarks get stripped, or only honest players bother to comply.\n- **So what:** Europe is deciding when apps and sites must tell you you’re talking to AI or seeing synthetic media. That shapes how much you can trust what you read, watch, and click—not just whether a label exists."
    }
  ],
  "featuredSparks": [
    "whose-opinions",
    "oracle",
    "the-state",
    "where-it-lives",
    "who-owns-temple"
  ]
};

// Custom sparks that are not in the dashboard's SPARK_LIBRARY yet.
// Add these to SPARK_LIBRARY before using their ids in featuredSparks.
const GENERATED_SPARKS = {};
