#!/usr/bin/env python3
"""Fetch lightweight page summaries for research inbox items.

Network is opt-in via --allow-network. Uses stdlib only.
Writes page-summaries.json and updates empty inbox summaries when safe.
"""

from __future__ import annotations

import argparse
import datetime as dt
import html as html_lib
import json
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
EPISODES_DIR = ROOT / "episodes"
TAG_RE = re.compile(r"<[^>]+>")
META_RE = {
    "description": re.compile(
        r'<meta[^>]+name=["\']description["\'][^>]+content=["\'](?P<value>[^"\']+)',
        re.I,
    ),
    "og_description": re.compile(
        r'<meta[^>]+property=["\']og:description["\'][^>]+content=["\'](?P<value>[^"\']+)',
        re.I,
    ),
    "title": re.compile(r"<title[^>]*>(?P<value>.*?)</title>", re.I | re.S),
}


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, content: str) -> None:
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def resolve_episode_dir(value: str) -> Path:
    if value:
        candidate = Path(value)
        if candidate.is_dir():
            return candidate.resolve()
        numbered = EPISODES_DIR / value
        if numbered.is_dir():
            return numbered.resolve()
        raise SystemExit(f"Episode folder not found: {value}")

    numbered_dirs = sorted(
        path for path in EPISODES_DIR.iterdir()
        if path.is_dir() and re.match(r"^\d{3}", path.name)
    )
    if not numbered_dirs:
        raise SystemExit(f"No numbered episode folders found under {EPISODES_DIR}")
    return numbered_dirs[-1].resolve()


def clean_html_text(value: str) -> str:
    text = TAG_RE.sub(" ", value)
    text = html_lib.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def fetch_url(url: str, timeout: int) -> str:
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": (
                "Mozilla/5.0 (compatible; ReelItInResearch/1.0; +https://github.com/ShanesNotes/reel-it-in)"
            )
        },
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:
        raw = response.read(500_000)
    return raw.decode("utf-8", errors="replace")


def summarize_html(page_html: str) -> dict[str, str]:
    summary = ""
    for pattern in (META_RE["og_description"], META_RE["description"]):
        match = pattern.search(page_html)
        if match:
            summary = clean_html_text(match.group("value"))
            break

    title_match = META_RE["title"].search(page_html)
    title = clean_html_text(title_match.group("value")) if title_match else ""

    if not summary:
        paragraphs = re.findall(r"<p[^>]*>(.*?)</p>", page_html, flags=re.I | re.S)
        for paragraph in paragraphs[:6]:
            text = clean_html_text(paragraph)
            if len(text) >= 80:
                summary = text[:400]
                break

    return {"title": title, "summary": summary}


def render_markdown(episode_name: str, records: list[dict[str, Any]]) -> str:
    lines = [
        "# Page Summaries",
        "",
        f"Generated by `tools/fetch-page-summaries.py` for `{episode_name}`.",
        "",
        "Lightweight page extracts to backfill empty research inbox summaries.",
        "",
    ]
    for record in records:
        lines.extend(
            [
                f"## {record.get('title') or record.get('feed', 'Story')}",
                "",
                f"- URL: {record.get('url', '')}",
                f"- Status: {record.get('fetchStatus', 'n/a')}",
                "",
                record.get("summary", "").strip() or "_No summary extracted._",
                "",
            ]
        )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--episode", default="", help="Episode folder name or path")
    parser.add_argument("--limit", type=int, default=8, help="Max inbox items to fetch")
    parser.add_argument("--timeout", type=int, default=20, help="HTTP timeout seconds")
    parser.add_argument(
        "--allow-network",
        action="store_true",
        help="Required to fetch source pages",
    )
    parser.add_argument("--dry-run", action="store_true", help="List target URLs only")
    args = parser.parse_args()

    episode_dir = resolve_episode_dir(args.episode)
    episode_name = episode_dir.name
    inbox_path = episode_dir / "research-inbox.json"
    if not inbox_path.exists():
        raise SystemExit(f"Missing research inbox: {inbox_path}")

    inbox = read_json(inbox_path)
    items = list(inbox.get("items", []))
    targets = [
        item for item in items
        if item.get("url") and not str(item.get("summary", "")).strip()
    ][: max(args.limit, 0)]

    if not targets:
        print("No inbox items with empty summaries found.")
        return 0

    if not args.allow_network and not args.dry_run:
        raise SystemExit(
            "Network opt-in required. Re-run with --allow-network to fetch pages."
        )

    generated_at = dt.datetime.now().replace(microsecond=0).isoformat()
    records: list[dict[str, Any]] = []

    for item in targets:
        url = str(item["url"])
        if args.dry_run:
            print(url)
            records.append({**item, "fetchStatus": "dry-run", "summary": ""})
            continue

        try:
            page_html = fetch_url(url, args.timeout)
            extracted = summarize_html(page_html)
            summary = extracted["summary"]
            status = "ok" if summary else "empty"
        except (urllib.error.URLError, TimeoutError, ValueError) as exc:
            extracted = {"title": "", "summary": ""}
            summary = ""
            status = f"error: {exc}"

        record = {
            "feed": item.get("feed", ""),
            "title": item.get("title", "") or extracted.get("title", ""),
            "url": url,
            "summary": summary,
            "fetchStatus": status,
        }
        records.append(record)

        if summary:
            for inbox_item in items:
                if inbox_item.get("url") == url and not str(inbox_item.get("summary", "")).strip():
                    inbox_item["summary"] = summary

    if args.dry_run:
        return 0

    payload = {
        "schemaVersion": 1,
        "generatedAt": generated_at,
        "episode": episode_name,
        "itemCount": len(records),
        "items": records,
    }
    write_json(episode_dir / "page-summaries.json", payload)
    write_text(episode_dir / "page-summaries.md", render_markdown(episode_name, records))
    write_json(inbox_path, inbox)
    print(f"Wrote {episode_dir / 'page-summaries.json'}")
    print(f"Updated {inbox_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())