[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [string]$Episode = "",
    [string]$OutputDir = "",
    [string]$Model = "gpt-image-1.5",
    [ValidateSet("1024x1024", "1536x1024", "1024x1536", "auto")]
    [string]$Size = "1536x1024",
    [ValidateSet("low", "medium", "high", "auto")]
    [string]$Quality = "medium",
    [ValidateRange(1, 8)]
    [int]$MaxImages = 4,
    [switch]$AllowPaidGeneration,
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$episodesDir = Join-Path $repoRoot "episodes"

function Resolve-EpisodeDirectory {
    param([string]$Value)

    if (-not [string]::IsNullOrWhiteSpace($Value)) {
        if (Test-Path -LiteralPath $Value) {
            return (Resolve-Path -LiteralPath $Value).Path
        }

        $candidate = Join-Path $episodesDir $Value
        if (Test-Path -LiteralPath $candidate) {
            return (Resolve-Path -LiteralPath $candidate).Path
        }

        throw "Episode folder not found: $Value"
    }

    $latest = Get-ChildItem -LiteralPath $episodesDir -Directory |
        Where-Object { $_.Name -match "^\d{3}" } |
        Sort-Object Name |
        Select-Object -Last 1

    if (-not $latest) {
        throw "No numbered episode folders found under $episodesDir"
    }

    return $latest.FullName
}

function ConvertTo-Slug {
    param([string]$Value)

    $slug = $Value.ToLowerInvariant() -replace "[^a-z0-9]+", "-"
    return $slug.Trim("-")
}

function Write-Utf8Text {
    param(
        [string]$Path,
        [string]$Content
    )

    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, $Content.Trim() + [Environment]::NewLine, $utf8NoBom)
}

function Write-Utf8Json {
    param(
        [string]$Path,
        [object]$Data
    )

    $json = $Data | ConvertTo-Json -Depth 20
    Write-Utf8Text -Path $Path -Content $json
}

function ConvertTo-RelativePath {
    param([string]$Path)

    if ($Path.StartsWith($repoRoot.Path, [System.StringComparison]::OrdinalIgnoreCase)) {
        return $Path.Replace("$($repoRoot.Path)\", "").Replace("\", "/")
    }

    return $Path
}

function Save-ImageResponse {
    param(
        [object]$Image,
        [string]$Path,
        [hashtable]$Headers
    )

    if ($Image.b64_json) {
        [System.IO.File]::WriteAllBytes($Path, [Convert]::FromBase64String($Image.b64_json))
        return
    }

    if ($Image.url) {
        Invoke-WebRequest -Uri $Image.url -Headers $Headers -OutFile $Path -TimeoutSec 180 | Out-Null
        return
    }

    throw "Image response did not include b64_json or url."
}

$episodeDir = Resolve-EpisodeDirectory -Value $Episode
$episodeName = Split-Path -Path $episodeDir -Leaf
$creativeJsonPath = Join-Path $episodeDir "title-thumbnail.json"
$manifestPath = Join-Path $episodeDir "thumbnail-images.json"
$marketingDir = Join-Path (Join-Path $episodeDir "handoff") "marketing"
$generatedThumbnailsPath = Join-Path $marketingDir "generated-thumbnails.md"

if (-not (Test-Path -LiteralPath $creativeJsonPath)) {
    throw "Missing title-thumbnail.json. Run tools/generate-title-thumbnail-package.ps1 first."
}

if ([string]::IsNullOrWhiteSpace($OutputDir)) {
    $documents = [Environment]::GetFolderPath("MyDocuments")
    $OutputDir = Join-Path (Join-Path $documents "Reel It In Media") (Join-Path $episodeName "thumbnails")
}
elseif (-not [System.IO.Path]::IsPathRooted($OutputDir)) {
    $OutputDir = Join-Path $repoRoot $OutputDir
}

$creative = Get-Content -LiteralPath $creativeJsonPath -Raw | ConvertFrom-Json
$options = @($creative.thumbnailOptions | Select-Object -First $MaxImages)
$apiKey = $env:OPENAI_API_KEY
$enabledByEnv = $env:REEL_IT_IN_GENERATE_IMAGES -eq "1"
$canGenerate = ($AllowPaidGeneration -or $enabledByEnv) -and -not [string]::IsNullOrWhiteSpace($apiKey)
$records = New-Object System.Collections.Generic.List[object]
$generatedAt = (Get-Date).ToString("s")

New-Item -ItemType Directory -Force -Path $marketingDir | Out-Null

if (-not $canGenerate) {
    $reason = if ([string]::IsNullOrWhiteSpace($apiKey)) {
        "OPENAI_API_KEY is not set."
    }
    else {
        "Paid generation is not enabled. Pass -AllowPaidGeneration or set REEL_IT_IN_GENERATE_IMAGES=1."
    }

    $content = @"
# Generated Thumbnails

Generated by ``tools/generate-thumbnail-images.ps1`` from ``$episodeName``.

## Status

Skipped image generation.

Reason: $reason

## To Generate

~~~powershell
`$env:OPENAI_API_KEY = "<your key>"
`$env:REEL_IT_IN_GENERATE_IMAGES = "1"
.\tools\generate-thumbnail-images.ps1 -Episode $episodeName
~~~

## Candidate Prompts

$(@($options | ForEach-Object { "### $($_.name)`n`n$($_.prompt)" }) -join "`n`n")
"@

    $manifest = [ordered]@{
        schemaVersion = 1
        generatedAt = $generatedAt
        episode = $episodeName
        status = "skipped"
        reason = $reason
        model = $Model
        size = $Size
        quality = $Quality
        outputDir = $OutputDir
        images = @()
    }

    if ($PSCmdlet.ShouldProcess($episodeDir, "Write skipped thumbnail generation manifest")) {
        Write-Utf8Text -Path $generatedThumbnailsPath -Content $content
        Write-Utf8Json -Path $manifestPath -Data $manifest
    }

    Write-Host "Thumbnail image generation skipped: $reason"
    Write-Host "Generated thumbnail handoff: $generatedThumbnailsPath"
    exit 0
}

New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
$headers = @{
    Authorization = "Bearer $apiKey"
}
$jsonHeaders = @{
    Authorization = "Bearer $apiKey"
    "Content-Type" = "application/json"
}

$index = 1
foreach ($option in $options) {
    $slug = ConvertTo-Slug -Value $option.name
    if ([string]::IsNullOrWhiteSpace($slug)) {
        $slug = "thumbnail-$index"
    }

    $fileName = "{0:D2}-{1}.png" -f $index, $slug
    $filePath = Join-Path $OutputDir $fileName

    if ((Test-Path -LiteralPath $filePath) -and -not $Force) {
        $records.Add([ordered]@{
            concept = $option.name
            overlay = $option.overlay
            prompt = $option.prompt
            status = "exists"
            path = $filePath
            relativePath = ConvertTo-RelativePath -Path $filePath
        })
        $index++
        continue
    }

    $body = [ordered]@{
        model = $Model
        prompt = $option.prompt
        n = 1
        size = $Size
        quality = $Quality
        output_format = "png"
    } | ConvertTo-Json -Depth 10

    try {
        if ($PSCmdlet.ShouldProcess($filePath, "Generate thumbnail image with $Model")) {
            $response = Invoke-RestMethod -Uri "https://api.openai.com/v1/images/generations" -Method Post -Headers $jsonHeaders -Body $body -TimeoutSec 240
            Save-ImageResponse -Image $response.data[0] -Path $filePath -Headers $headers
        }

        $records.Add([ordered]@{
            concept = $option.name
            overlay = $option.overlay
            prompt = $option.prompt
            status = "generated"
            path = $filePath
            relativePath = ConvertTo-RelativePath -Path $filePath
        })
    }
    catch {
        $records.Add([ordered]@{
            concept = $option.name
            overlay = $option.overlay
            prompt = $option.prompt
            status = "failed"
            error = $_.Exception.Message
            path = $filePath
            relativePath = ConvertTo-RelativePath -Path $filePath
        })
    }

    $index++
}

$imageLines = New-Object System.Collections.Generic.List[string]
foreach ($record in $records) {
    $imageLines.Add("## $($record.concept)")
    $imageLines.Add("")
    $imageLines.Add("- Status: $($record.status)")
    $imageLines.Add("- Overlay: $($record.overlay)")
    $imageLines.Add("- Path: ``$($record.path)``")
    if ($record.error) {
        $imageLines.Add("- Error: $($record.error)")
    }
    $imageLines.Add("")
}

$generatedContent = @"
# Generated Thumbnails

Generated by ``tools/generate-thumbnail-images.ps1`` from ``$episodeName``.

## Settings

- Model: $Model
- Size: $Size
- Quality: $Quality
- Output folder: ``$OutputDir``

$($imageLines -join "`n")
"@

$manifest = [ordered]@{
    schemaVersion = 1
    generatedAt = $generatedAt
    episode = $episodeName
    status = "complete"
    model = $Model
    size = $Size
    quality = $Quality
    outputDir = $OutputDir
    images = $records.ToArray()
}

if ($PSCmdlet.ShouldProcess($episodeDir, "Write generated thumbnail manifest")) {
    Write-Utf8Text -Path $generatedThumbnailsPath -Content $generatedContent
    Write-Utf8Json -Path $manifestPath -Data $manifest
}

$generatedCount = @($records | Where-Object { $_.status -eq "generated" }).Count
$failedCount = @($records | Where-Object { $_.status -eq "failed" }).Count
Write-Host "Generated thumbnails: $generatedCount"
Write-Host "Failed thumbnails: $failedCount"
Write-Host "Thumbnail manifest: $manifestPath"
Write-Host "Thumbnail handoff:  $generatedThumbnailsPath"
